config/routes.rb
Rails.application.routes.draw do
  match 'todos/list', :controller => 'todos', :action => 'list', via: :get
  get 'todos', to: 'todos#index'
  get '/todos/new'
  post 'todos',  to: 'todos#create'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'edit'
  patch 'todos/:id', to: 'todos#update', as: 'update'
  delete 'todos/:id', to: 'todos#destroy', as: 'delete'
  get 'todos/:id', to: 'todos#complete', as: 'complete'
  #get 'todos/list' to: 'todos#list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :find_todo, only: [:show, :edit, :update, :destroy]

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to todos_path
  end

  def show
  end

  def edit
  end

  def update
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def destroy
    @todo.destroy
    redirect_to todos_path
  end

  def list
    @todos = Todo.all
  end

  private

  def todo_params
    params.require(:todo).permit(:description, :completed)
  end

  def find_todo
  @todo = Todo.find(params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/united/bootstrap.min.css">

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar'%>
    <%= yield %>
  </body>

</html>

app/views/todos/_form.html.erb
<div class="container well">

    <%=form_with model: @todo, local: true do |f| %>
      <%= f.label "Todo Description" %>
      <%= f.text_field :description %>
      <br>
      <br>

      <%= f.label "Mark only when completed" %>
      <%= f.hidden_field :completed %>
      <%= f.check_box :completed %>
      <br>
      <%= f.submit "Save Todo" %>
    <% end %>
</div>

app/views/todos/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Todos Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Índex', todos_path %></li>
        <li><%= link_to 'list', todos_list_path %></li>
        <li><%= link_to 'Crear', todos_new_path %></li>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ToDos</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
            <li><%= link_to 'Index', todos_path %></li>
            <li><%= link_to 'ToDo list', todos_list_path %></li>
            <li><%= link_to 'Create new ToDo', todos_new_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/todos/edit.html.erb
		<%= render 'form' %>


<div class="container link">
	<h3> <%= link_to 'back', todos_path %> </h3>
</div>

app/views/todos/index.html.erb
<div class="container">
  <h4>  <%= link_to 'Create new Todo',  todos_new_path %> </h4>
  <br>
  <% @todos.each do |todo| %>
    <div class="well">
      <div class="col-md-6">
        <%= todo.description %>
     </div>
     <div class="col-md-6">
       <p class="complete"><%= 'Completed' if todo.completed == true %><p>
       <p class="pending"><%= 'Pending' if todo.completed == false %><p>
    </div>

      <hr />
      <%= link_to 'Show', todo %> |
      <%= link_to "Edit", edit_path(todo.id) %> |
      <%= link_to 'Delete', todo, 'data-confirm' => 'Are you sure?', :method => :delete %>
    </div>
  <% end %>
</div>

app/views/todos/list.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-md-6">
        <h2 class="">Pending ToDos</h2>
          <div class="well">
          <% @todos.each do |todo| %>
          <p> <%= todo.description if todo.completed == false %> </p>
          <br>
          <% end %>
          </div>

        </div>
        <div class="col-md-6">
        <h2 class="">Completed ToDos</h2>

          <div class="well">
          <% @todos.each do |todo| %>
          <p> <%= todo.description if todo.completed == true %> </p>
          <br>
          <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/todos/new.html.erb
  <%= render 'form' %>

<div class="container">
	<h3><%= link_to 'back', todos_path %></h3>
</div>

app/views/todos/show.html.erb
<div class="container">
	<div class="well row">
		<div class="col-md-4">
			<h3> Description </h3>
			<p><%= @todo.description %></p>
			<small> Created : <%= time_ago_in_words @todo.created_at %> </small>

		</div>

		<div class="col-md-4">
		  <h3> Status </h3>
						<%= 'Completed' if @todo.completed == true %>
						<%= 'Pending' if @todo.completed == false %>
		</div>
	</div>
		<h3> <%= link_to 'Back', todos_path %> </h3>
</div>